import {
  Boxes,
  Check,
  CircleDashed,
  GitMerge,
  Network,
  Search,
  ShieldCheck,
  Truck,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { AgentProjection, CaseProjection } from "../application/caseProjector";

interface AgentWorkbenchProps {
  projection: CaseProjection;
}

interface AgentCardProps {
  name: string;
  role: string;
  agent: AgentProjection;
  icon: LucideIcon;
  systems: readonly string[];
  parallel?: boolean;
}

const agentStatusLabel = {
  waiting: "Waiting",
  running: "Running",
  complete: "Complete",
} as const;

function AgentCard({ name, role, agent, icon: Icon, systems, parallel }: AgentCardProps) {
  return (
    <article className="agent-card" data-status={agent.state}>
      <div className="agent-topline">
        <div className="agent-name">
          <span className="agent-icon" aria-hidden="true"><Icon size={17} /></span>
          <div>
            <h3>{name}</h3>
            <span>{role}</span>
          </div>
        </div>
        <span className="agent-status">
          {agent.state === "complete" ? <Check size={11} /> : <CircleDashed size={11} />}
          {agentStatusLabel[agent.state]}
        </span>
      </div>
      <div className="agent-body">
        <p className="agent-section-label">Simulated deterministic reasoning</p>
        <p className="agent-copy">
          {agent.reasoningSummary ??
            (agent.state === "running"
              ? "Evaluating the available event context against transparent scenario rules."
              : "Waiting for the prerequisite business event.")}
        </p>
        <p className="agent-section-label">Illustrative source systems</p>
        <div className="source-tags">
          {systems.map((system) => <span className="source-tag" key={system}>{system}</span>)}
        </div>
        {agent.outputIds.length ? (
          <p className="agent-copy" style={{ marginTop: 10, marginBottom: 0 }}>
            Output: <span className="mono">{agent.outputIds.join(", ")}</span>
          </p>
        ) : null}
        {parallel ? (
          <div className="independent-note" style={{ color: "var(--ink-soft)" }}>
            <Network size={13} aria-hidden="true" />
            Independent branch · no access to the peer proposal
          </div>
        ) : null}
      </div>
    </article>
  );
}

const currency = (value: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

const dateTime = (value: string) =>
  new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    timeZone: "UTC",
  }).format(new Date(value));

export function AgentWorkbench({ projection }: AgentWorkbenchProps) {
  const evaluationByPlan = new Map(projection.evaluations.map((item) => [item.planId, item]));
  const recommendation = projection.evaluations.find(
    (item) => item.planId === projection.recommendedPlanId,
  );

  return (
    <>
      <section className="panel content-panel" aria-labelledby="agents-title">
        <div className="section-heading">
          <div>
            <p className="section-kicker">Agent workbench</p>
            <h2 id="agents-title">Independent analysis, explicit hand-offs</h2>
          </div>
          <p>
            “Agents” are deterministic scenario services. Their reasoning is simulated,
            rule-based and inspectable—not generated by a live model.
          </p>
        </div>
        <div className="agent-grid">
          <AgentCard
            name="Impact agent"
            role="Resolve affected commitments"
            agent={projection.agents.impact}
            icon={Search}
            systems={["S/4HANA order book", "SAP Datasphere", "Knowledge graph"]}
          />
          <AgentCard
            name="Sourcing agent"
            role="Find supply-side alternatives"
            agent={projection.agents.sourcing}
            icon={Boxes}
            systems={["SAP Ariba network", "Inventory positions"]}
            parallel
          />
          <AgentCard
            name="Logistics agent"
            role="Find transport alternatives"
            agent={projection.agents.logistics}
            icon={Truck}
            systems={["SAP TM", "Carrier / 3PL APIs"]}
            parallel
          />
          <AgentCard
            name="Supervisor agent"
            role="Gather proposals and apply policy"
            agent={projection.agents.supervisor}
            icon={GitMerge}
            systems={["Margin & SLA policy", "Cost to serve", "Customer tier"]}
          />
        </div>
      </section>

      <section className="panel content-panel" aria-labelledby="orders-title">
        <div className="section-heading">
          <div>
            <p className="section-kicker">Business impact</p>
            <h2 id="orders-title">Impacted orders</h2>
          </div>
          <p>Projected dates and service exposure appear after impact assessment.</p>
        </div>
        {projection.orders.length ? (
          <div className="table-wrap" tabIndex={0} aria-label="Scrollable impacted orders table">
            <table className="data-table">
              <caption>Orders affected by the MV Horizon delay</caption>
              <thead>
                <tr>
                  <th>Order / customer</th>
                  <th>Tier</th>
                  <th>Destination</th>
                  <th>Promised UTC</th>
                  <th>Projected delay</th>
                  <th>SLA exposure</th>
                </tr>
              </thead>
              <tbody>
                {projection.orders.map((order) => (
                  <tr key={order.orderId}>
                    <td><strong>{order.orderId}</strong><br />{order.customerName}</td>
                    <td><span className="tier" data-tier={order.customerTier[0] + order.customerTier.slice(1).toLowerCase()}>{order.customerTier}</span></td>
                    <td>{order.destination}</td>
                    <td>{dateTime(order.promisedDeliveryAt)}</td>
                    <td><strong>{order.projectedDelayHours} hours</strong></td>
                    <td><strong>{currency(order.slaExposureUsd)}</strong></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p className="agent-copy">No orders have been assessed. Advance the case after the carrier signal.</p>
        )}
      </section>

      <section className="panel content-panel" aria-labelledby="plans-title">
        <div className="section-heading">
          <div>
            <p className="section-kicker">Options & policy</p>
            <h2 id="plans-title">Three-plan comparison</h2>
          </div>
          <p>The supervisor waits for both branches before comparing proposals.</p>
        </div>
        {projection.plans.length ? (
          <div className="plan-list">
            {projection.plans.map((plan) => {
              const evaluation = evaluationByPlan.get(plan.planId);
              return (
                <article
                  className="plan-row"
                  key={plan.planId}
                  data-recommended={plan.planId === projection.recommendedPlanId}
                >
                  <div className="plan-name">
                    <strong>{plan.title}</strong>
                    <span>{plan.source} · {plan.planId}</span>
                  </div>
                  <div className="plan-metric"><strong>{plan.etaRecoveryHours}h</strong><span>ETA recovery</span></div>
                  <div className="plan-metric"><strong>{currency(plan.incrementalCostUsd)}</strong><span>Incremental cost</span></div>
                  <div className="plan-metric"><strong>{plan.projectedMarginPercent.toFixed(1)}%</strong><span>Margin</span></div>
                  <div className="plan-metric"><strong>{plan.ordersMeetingSla}/{plan.totalOrders}</strong><span>SLAs protected</span></div>
                  <span className="policy-chip" data-eligible={evaluation?.eligible ?? false}>
                    {evaluation ? (evaluation.eligible ? "Eligible" : "Ineligible") : "Pending policy"}
                  </span>
                </article>
              );
            })}
          </div>
        ) : (
          <p className="agent-copy">Options will appear after the parallel sourcing and logistics branch completes.</p>
        )}
        {recommendation ? (
          <div style={{ marginTop: 18 }}>
            <p className="agent-section-label">Why the supervisor recommends {recommendation.planId}</p>
            <p className="agent-copy">{recommendation.explanation}</p>
            <div className="reason-grid">
              {recommendation.rules.map((rule) => (
                <div className="reason-item" key={rule.rule}>
                  {rule.passed ? <Check size={15} color="var(--success)" aria-hidden="true" /> : <ShieldCheck size={15} color="var(--warning)" aria-hidden="true" />}
                  <span><strong>{rule.rule.replaceAll("-", " ")}</strong><br />{rule.explanation}<br /><span className="mono">{rule.actual} · {rule.threshold}</span></span>
                </div>
              ))}
            </div>
          </div>
        ) : null}
      </section>
    </>
  );
}
